version: "3.9"

services:
  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  next:
    container_name: nextts
    image: instalog
    build:
      context: ./instalog
      dockerfile: ../docker/dev/Dockerfile

    depends_on:
      - db
    ports:
      - "3000:3000"
      - "5555:5555"
    command: tail -f /dev/null
    volumes:
      - ./instalog:/var/www

volumes:
  pgdata: {}